spring:
  application:
    name: bus_ticket

  datasource:
    url: jdbc:mysql://localhost:3306/bus_ticket
    username: root
    password: Manh2004

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/realms/bus_ticket
      client:
        registration:
          bus_ticket:
            client-secret: oAxwdQpjseeMeUGzC4v6UbScqPS5v9MN
            client-id: bus_ticket
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
            redirect-uri: http://localhost:3000/login/oauth2/code/bus_ticket
        provider:
          bus_ticket:
            issuer-uri: http://localhost:8080/realms/bus_ticket
            token-uri: http://localhost:8080/realms/bus_ticket/protocol/openid-connect/token

server:
  port: 8081

cloudinary:
  api_key: 829565713471837
  api_secret: oHpiWWc8qqRFZUkj-kBtXhsVcJ8
  cloud_name: djuq2enmy

